<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="My sample suite" duration-ms="56045" started-at="2015-07-05T17:40:42Z" finished-at="2015-07-05T17:41:38Z">
    <groups>
    </groups>
    <test name="Learning Test" duration-ms="36243" started-at="2015-07-05T17:40:42Z" finished-at="2015-07-05T17:41:18Z">
      <class name="SeleniumStart.DynamicBrowser">
        <test-method status="PASS" signature="testDynamicBrowser()[pri:0, instance:SeleniumStart.DynamicBrowser@a9e816]" name="testDynamicBrowser" duration-ms="36200" started-at="2015-07-05T23:10:42Z" finished-at="2015-07-05T23:11:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDynamicBrowser -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:SeleniumStart.DynamicBrowser@a9e816]" name="quitDriver" is-config="true" duration-ms="24" started-at="2015-07-05T23:11:18Z" finished-at="2015-07-05T23:11:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- SeleniumStart.DynamicBrowser -->
    </test> <!-- Learning Test -->
    <test name="Learning Assertions" duration-ms="19772" started-at="2015-07-05T17:41:18Z" finished-at="2015-07-05T17:41:38Z">
      <class name="SeleniumStart.TestNGSample">
        <test-method status="PASS" signature="initDriver()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="initDriver" is-config="true" duration-ms="12228" started-at="2015-07-05T23:11:18Z" finished-at="2015-07-05T23:11:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initDriver -->
        <test-method status="FAIL" signature="testSample()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="testSample" duration-ms="7526" started-at="2015-07-05T23:11:30Z" finished-at="2015-07-05T23:11:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at SeleniumStart.TestNGSample.testSample(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSample -->
        <test-method status="PASS" signature="testBeforeEachTest()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="testBeforeEachTest" is-config="true" duration-ms="0" started-at="2015-07-05T23:11:30Z" finished-at="2015-07-05T23:11:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBeforeEachTest -->
        <test-method status="PASS" signature="AfterEachMethod()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="AfterEachMethod" is-config="true" duration-ms="1" started-at="2015-07-05T23:11:38Z" finished-at="2015-07-05T23:11:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterEachMethod -->
        <test-method status="PASS" signature="AfterEachMethod()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="AfterEachMethod" is-config="true" duration-ms="1" started-at="2015-07-05T23:11:38Z" finished-at="2015-07-05T23:11:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterEachMethod -->
        <test-method status="PASS" signature="testBeforeEachTest()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="testBeforeEachTest" is-config="true" duration-ms="0" started-at="2015-07-05T23:11:38Z" finished-at="2015-07-05T23:11:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBeforeEachTest -->
        <test-method status="SKIP" signature="testSample1()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="testSample1" duration-ms="0" started-at="2015-07-05T23:11:38Z" finished-at="2015-07-05T23:11:38Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipped
	at SeleniumStart.TestNGSample.testSample1(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSample1 -->
        <test-method status="PASS" signature="quitDriver()[pri:0, instance:SeleniumStart.TestNGSample@1f4f00f]" name="quitDriver" is-config="true" duration-ms="15" started-at="2015-07-05T23:11:38Z" finished-at="2015-07-05T23:11:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- SeleniumStart.TestNGSample -->
    </test> <!-- Learning Assertions -->
  </suite> <!-- My sample suite -->
</testng-results>
